# Bài 1:
Vào 1 đường dẫn đến tập các file text (chỉ vào thư mục, tên file và số lượng file không biết), in ra các từ và số lượng các từ trong tất cả các file đó, giả sử các từ cách nhau bởi khoảng trắng.<br>
`Ví dụ: vào thư mục Task1/data trong thư mục này có 3 file text: T1.txt, T2.txt, T3.txt`
- T1.txt: Hello World Hello World
- T2.txt: Hello Hello
- T3.txt: World I am <br>
`Ra Output.txt:`
- Hello: 4
- World: 3
- I: 1
- am: 1

`Đường dẫn trong bài:` **Task1/data**

In [3]:
import os

def count_words(directory):
    words = {}
    for file in os.listdir(directory):
        with open(os.path.join(directory, file)) as f:
            for word in f.read().split():
                words[word] = words.get(word, 0) + 1
    return words

if __name__ == "__main__":
    while True:
        directory = input("Nhập đường dẫn thư mục: ")
        try:
            words = count_words(directory)
            with open(os.path.join(directory, "Output.txt"), "w") as f:
                for word, count in words.items():
                    f.write(f"{word}: {count}\n")
            print("Output.txt đã được tạo thành công!")
            break  # Thoát khỏi vòng lặp nếu thư mục hợp lệ và xử lý đã hoàn thành
        except FileNotFoundError:
            print("Thư mục không tìm thấy. Vui lòng nhập một đường dẫn thư mục hợp lệ.")
    
    # In kết quả ra màn hình để kiểm tra
    print("Kết quả của file Output.txt:")
    with open(os.path.join(directory, "Output.txt")) as f:
        print(f.read())


Output.txt đã được tạo thành công!
Kết quả của file Output.txt:
Hello: 4
World: 3
I: 1
Am: 1



# Bài 2:
Viết chương trình để map key value trong 2 từ điển:<br>
`Ví dụ:` {'key1': 1, 'key2': 3, 'key3': 2}, {'key1': 1, 'key2': 2} <br>
`Kết quả:` key1: 1 is present in both x and y

In [7]:
def compare_dicts(dict1, dict2):
    common_keys = set(dict1) & set(dict2)
    for key in common_keys: 
        if dict1[key] == dict2[key]: 
            print(f"{key}: {dict1[key]} is present in both x and y")

x = {'key1': 1, 'key2': 1, 'key3': 2}
y = {'key1': 1, 'key2': 2}

compare_dicts(x, y)

key1: 1 is present in both x and y


# Bài 3:
Viết chương trình để lưu dữ liệu từ 1 từ điển thành 1 file json <br>
`Ví dụ Từ điển:` <br>
{'students': [{'firstName': 'Nikki', 'lastName': 'Roysden'}, {'firstName': 'Mervin', 'lastName':
'Friedland'}, {'firstName': 'Aron ', 'lastName': 'Wilkins'}], <br>'teachers': [{'firstName': 'Amberly',
'lastName': 'Calico'}, {'firstName': 'Regine', 'lastName': 'Agtarap'}]}

In [10]:
import json
import os

# Dữ liệu từ điển
data_dict = {
    'students': [
        {'firstName': 'Nikki', 'lastName': 'Roysden'},
        {'firstName': 'Mervin', 'lastName': 'Friedland'},
        {'firstName': 'Aron', 'lastName': 'Wilkins'}
    ],
    'teachers': [
        {'firstName': 'Amberly', 'lastName': 'Calico'},
        {'firstName': 'Regine', 'lastName': 'Agtarap'}
    ]
}

# Đường dẫn đến thư mục Task4
folder_path = 'Task4'

# Tạo thư mục nếu chưa tồn tại
if not os.path.exists(folder_path):
    os.makedirs(folder_path)

# Đường dẫn tới tệp JSON trong thư mục Task4
file_path = os.path.join(folder_path, 'data.json')

# Lưu dữ liệu từ điển vào tệp JSON
with open(file_path, 'w') as json_file:
    json.dump(data_dict, json_file, indent=4) # indent=4: thụt lề 4 khoảng trắng

# Thông báo lưu thành công
print('Lưu thành công')

Lưu thành công


`Kết quả của file data.json là:`
```python
{
    "students": [
        {
            "firstName": "Nikki",
            "lastName": "Roysden"
        },
        {
            "firstName": "Mervin",
            "lastName": "Friedland"
        },
        {
            "firstName": "Aron",
            "lastName": "Wilkins"
        }
    ],
    "teachers": [
        {
            "firstName": "Amberly",
            "lastName": "Calico"
        },
        {
            "firstName": "Regine",
            "lastName": "Agtarap"
        }
    ]
}
```

# Bài 4:
Viết chương trình sử dụng thư viện numpy để tính:
- the multiplication of two given matrixes.
- the outer product of two given vectors
- the cross product of two given vectors
- the determinant of a given square array
- the determinant of an array
- the inner product of vectors for 1-D arrays (without complex conjugation) and in
higher dimension

In [11]:
import numpy as np

# Multiplication of two given matrixes (Tích hai ma trận cho trước)
def matrix_multiplication(A, B):
    """Multiply two given matrixes."""
    return np.matmul(A, B)

# Outer product of two given vectors (Tích vô hướng hai vector cho trước)
def outer_product(a, b):
    """Compute the outer product of two given vectors."""
    return np.outer(a, b)

# Cross product of two given vectors (Tích có hướng hai vector cho trước)
def cross_product(a, b):  
    """Compute the cross product of two given vectors.""" 
    return np.cross(a, b)

# Determinant of a given square array (Định thức của một ma trận vuông cho trước)
def determinant(A):
    """Compute the determinant of a given square array."""
    return np.linalg.det(A)

# Determinant of an array (Định thức của một mảng cho trước)
def determinant_array(A):
    """Compute the determinant of an array."""
    if A.ndim == 2:
        return np.linalg.det(A)
    else:
        raise NotImplementedError("Determinant of array of dimension > 2 is not implemented yet.")

# Inner product of vectors for 1-D arrays (without complex conjugation) and in higher dimension (Tích trong hai vector cho trước)
def inner_product(a, b):
    """Compute the inner product of two vectors."""
    if a.ndim == 1 and b.ndim == 1:
        return np.dot(a, b)
    else:
        raise NotImplementedError("Inner product of vectors of dimension > 1 is not implemented yet.")

if __name__ == "__main__":
    A = np.array([[1, 2], [3, 4]]) 
    B = np.array([[5, 6], [7, 8]]) 
    print("Multiplication of two given matrixes:") 
    print(matrix_multiplication(A, B))

    v1 = np.array([1, 2, 3])
    v2 = np.array([4, 5, 6])
    print("Outer product of two given vectors:")
    print(outer_product(v1, v2))

    print("Cross product of two given vectors:")
    print(cross_product(v1, v2))

    print("Determinant of a given square array:")
    print(round(determinant(A), 4))

    print("Determinant of an array:")
    print(round(determinant_array(np.array([[1, 2], [3, 4]])), 4))

    print("Inner product of vectors for 1-D arrays (without complex conjugation):")
    print(inner_product(v1, v2))


Multiplication of two given matrixes:
[[19 22]
 [43 50]]
Outer product of two given vectors:
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Cross product of two given vectors:
[-3  6 -3]
Determinant of a given square array:
-2.0
Determinant of an array:
-2.0
Inner product of vectors for 1-D arrays (without complex conjugation):
32


# Bài 5:
Xây dựng cấu trúc Stack theo cú pháp sau:
```python
class Stack:
    def __init__(self):
        self.st = []
    def push(self,el):
    def pop(self):
    def isEmpty(self):
    def size(self):
    def top(self):
if __name__ == '__main__':
    st = Stack()
    st.push(5)
    st.push(7)
    st.push(9)
    print(st.pop())
    print(st.top())
```
Và sử dụng Stack để nhập vào 1 số ở dạng thập phân, in ra số đó ở hệ nhị phân
tương ứng. Ví dụ vào số 10 ra số 1010

In [12]:
class Stack:
    def __init__(self):
        self.st = []

    def push(self, el):
        self.st.append(el)

    def pop(self):
        return self.st.pop()

    def isEmpty(self):
        return len(self.st) == 0

    def size(self):
        return len(self.st)

    def top(self):
        return self.st[-1]


if __name__ == "__main__":
    st = Stack()
    st.push(5)
    st.push(7)  
    st.push(9)  
    print(st.pop())
    print(st.top())  
    
    # Sử dụng Stack để nhập vào 1 số ở dạng thập phân, in ra số đó ở hệ nhị phân tương ứng
    number = int(input("Enter a decimal number: "))
    stack = Stack()

    while number > 0:
        remainder = number % 2
        stack.push(remainder)
        number //= 2

    binary_number = ""

    while not stack.isEmpty():
        binary_number += str(stack.pop())

    print("The binary number is: " + binary_number)


9
7
The binary number is: 1010


# Bài 6: Xây dựng cấu trúc Stack
`Viết các hàm để tính các số phép toán + - * / với các số nguyên lớn` <br>

`Cài thư viện:` !pip install gmpy2 <br>
```python
    Add(bigIntA, bigIntB)
    Sub(bigIntA, bigIntB)
    Mul(bigIntA, bigIntB)
    Div(bigIntA, bigIntB)
```

In [28]:
from collections import deque

class BigIntStack:
    def __init__(self):
        self.stack = deque()

    def push(self, value):
        self.stack.append(value)

    def pop(self):
        if not self.empty():
            return self.stack.pop()
        else:
            raise ValueError("Stack is empty")

    def peek(self):
        if not self.empty():
            return self.stack[-1]
        else:
            raise ValueError("Stack is empty")

    def empty(self):
        return len(self.stack) == 0

def add(bigIntA, bigIntB):
    stackA = BigIntStack()
    stackB = BigIntStack()
    
    for digit in bigIntA:
        stackA.push(int(digit))
    for digit in bigIntB:
        stackB.push(int(digit))
    
    result = []
    carry = 0
    
    while not stackA.empty() or not stackB.empty() or carry:
        digitA = stackA.pop() if not stackA.empty() else 0
        digitB = stackB.pop() if not stackB.empty() else 0
        
        total = digitA + digitB + carry
        result.append(str(total % 10))
        carry = total // 10
    
    return ''.join(result[::-1])

def sub(bigIntA, bigIntB):
    stackA = BigIntStack()
    stackB = BigIntStack()
    
    for digit in bigIntA:
        stackA.push(int(digit))
    for digit in bigIntB:
        stackB.push(int(digit))
    
    result = []
    borrow = 0
    
    while not stackA.empty() or not stackB.empty():
        digitA = stackA.pop() if not stackA.empty() else 0
        digitB = stackB.pop() if not stackB.empty() else 0
        
        diff = digitA - digitB - borrow
        
        if diff < 0:
            diff += 10
            borrow = 1
        else:
            borrow = 0
        
        result.append(str(diff))
    
    return ''.join(result[::-1])

    
def mul(bigIntA, bigIntB):
    stackA = BigIntStack()
    
    for digit in bigIntA:
        stackA.push(int(digit))
    
    result = [0] * (len(bigIntA) + len(bigIntB))
    
    for i in range(len(bigIntA)):
        carry = 0
        digitA = stackA.pop()
        
        for j in range(len(bigIntB)):
            digitB = int(bigIntB[len(bigIntB) - 1 - j])
            product = digitA * digitB + carry + result[i + j]
            
            carry = product // 10
            result[i + j] = product % 10
        
        result[i + len(bigIntB)] += carry
    
    while len(result) > 1 and result[-1] == 0:
        result.pop()
    
    return ''.join(map(str, result[::-1]))

def div(bigIntA, bigIntB):
    if int(bigIntB) == 0:
        raise ValueError("Division by zero")

    quotient = []
    remainder = ""
    index = 0

    while index < len(bigIntA):
        remainder += bigIntA[index]
        quotient_digit = 0

        while int(remainder) >= int(bigIntB):
            quotient_digit += 1
            remainder = sub(remainder, bigIntB)

        quotient.append(str(quotient_digit))
        index += 1

    quotient = ''.join(quotient).lstrip('0')
    if quotient == "":
        quotient = "0"

    return quotient


# Example usage
bigIntA = "1234567890123456789012222324567890"
bigIntB = "987654321098765432109876543210"

print("Addition:", add(bigIntA, bigIntB))
print("Subtraction:", sub(bigIntA, bigIntB))
print("Multiplication:", mul(bigIntA, bigIntB))
print("Division:", div(bigIntA, bigIntB))

Addition: 1235555544444555554444332201111100
Subtraction: 1233580235802358023580112448024680
Multiplication: 1219326311370217952261728495897094539631151168641990410163526900
Division: 1249
